# Generated by Django 6.0.3 on 2026-03-11 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_wallets_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Wallet = apps.get_model('shop', 'Wallet')
    for user in User.objects.all():
        Wallet.objects.get_or_create(user=user, defaults={'balance': 0})


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_wallets_for_existing_users),
    ]
