# Generated by Django 5.2.11 on 2026-03-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_add_password_reset_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('purchase', 'Purchase'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In')], max_length=20),
        ),
    ]
