# Generated by Django 5.2.11 on 2026-03-12 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_update_transaction_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota2item',
            name='category',
            field=models.CharField(choices=[('core', 'Core'), ('support', 'Support'), ('neutral', 'Neutral'), ('consumable', 'Consumable'), ('hero_skin', 'Hero Skin')], default='core', max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='shop.dota2item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquired_at'],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
