# Generated by Django 5.2.11 on 2026-03-12 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_add_inventory_and_hero_skin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('purchase', 'Purchase'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('voucher', 'Voucher')], max_length=20),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('wallet', 'Wallet Credit'), ('item', 'Item / Skin')], max_length=10)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount (for wallet type)', max_digits=10)),
                ('item_quantity', models.PositiveIntegerField(default=1)),
                ('max_claims', models.PositiveIntegerField(default=1, help_text='Total allowed claims across all users')),
                ('times_claimed', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, help_text='Item to grant (for item type)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.dota2item')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_claims', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='shop.voucher')),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
    ]
