# Generated by Django 5.2.11 on 2026-03-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_add_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_static',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
